In [2]:
import numpy as np
import sys
import os
sys.path.append(os.path.join('..', 'importantfunctions'))
from integrationmethods import *

In [3]:
def f(t):
    return np.exp(-(t**2))

In [4]:
f(7)

5.242885663363464e-22

In [5]:
np.arange(0,3+0.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [6]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [7]:
np.arange(0,3+0.1,0.1).size

31

In [8]:
def ftest(x): #tested with this function first
    return x**4-2*x+1

In [9]:
def errortest(calctype,I1,I2):
    if calctype=='trapezoid':
        return (1/3)*abs(I2-I1)
    elif calctype=='simpsons':
        return (1/15)*abs(I2-I1)
    else:
        print("Can't estimate error for this calc type.")

In [10]:
epsilon=10**-3
N=2
I1=trapezoid(ftest,0,2,N=N)
I2=trapezoid(ftest,0,2,N=N*2)
error=errortest('trapezoid',I1,I2)

In [11]:
while error>epsilon:
    N*=2
    I1=I2
    I2=trapezoid(ftest,0,2,N=N*2)
    print(N,I1,I2)
    error=errortest('trapezoid',I1,I2)


4 11.5625 7.81640625
8 7.81640625 6.066650390625
16 6.066650390625 5.2229156494140625
32 5.2229156494140625 4.808854103088379
64 4.808854103088379 4.603776037693024
128 4.603776037693024 4.501725260168314
256 4.501725260168314 4.450821940088645
512 4.450821940088645 4.4254007975250715
1024 4.4254007975250715 4.41269785563145
2048 4.41269785563145 4.4063482920328525
4096 4.4063482920328525 4.403173987070752
8192 4.403173987070752 4.401586953798947


In [12]:
print(I2)

4.401586953798947


In [13]:
adaptivetrapezoid(ftest,0,2)

4 11.5625 7.81640625
8 7.81640625 6.066650390625
16 6.066650390625 5.2229156494140625
32 5.2229156494140625 4.808854103088379
64 4.808854103088379 4.603776037693024
128 4.603776037693024 4.501725260168314
256 4.501725260168314 4.450821940088645
512 4.450821940088645 4.4254007975250715
1024 4.4254007975250715 4.41269785563145
2048 4.41269785563145 4.4063482920328525
4096 4.4063482920328525 4.403173987070752
8192 4.403173987070752 4.401586953798947


4.401586953798947

In [26]:
adaptivesimpsons(ftest,0,2)

4 4.416666666666667 4.401041666666667
8 4.401041666666667 4.400065104166667


4.400065104166667

In [41]:
def trapezoidvector(function, a, b, N): #asked claude for help on how to vectorize this but implemented on my own
    vectorf=np.vectorize(function)

    deltax=(b-a)/N
    Ks=np.arange(1,N+1) #goes to N since arange doesn't include the endpoint
    Xs=a+Ks*deltax

    Fs=vectorf(Xs)
    mysum=np.sum(vectorf(Xs)) #sum the output of all the f(x)'s

    fa=function(a)
    fb=function(b)
    return deltax*(0.5*fa+0.5*fb+mysum), Xs, Fs

In [ ]:
def nestedtrap(function, a, b, Nprev):
    

In [51]:
trapezoidvector(ftest,0,2,N=16)

(6.066650390625,
 array([0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   , 1.125,
        1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ]),
 array([ 0.75024414,  0.50390625,  0.26977539,  0.0625    , -0.09741211,
        -0.18359375, -0.16381836,  0.        ,  0.35180664,  0.94140625,
         1.82446289,  3.0625    ,  4.72290039,  6.87890625,  9.60961914,
        13.        ]))

In [49]:
# epsilon=10**-5
# N=2
# I1,_,_=trapezoidvector(ftest,0,2,N=N)
# I2,_,_=trapezoidvector(ftest,0,2,N=N*2)
# error=errortest('trapezoid',I1,I2)
# while error>epsilon:
#     N*=2
#     I1=I2
#     I2,_,_=trapezoidvector(ftest,0,2,N=N*2)
#     print(N,I1,I2)
#     error=errortest('trapezoid',I1,I2)

4 11.5625 7.81640625
8 7.81640625 6.066650390625
16 6.066650390625 5.2229156494140625
32 5.2229156494140625 4.808854103088379
64 4.808854103088379 4.603776037693024
128 4.603776037693024 4.501725260168314
256 4.501725260168314 4.450821940088645
512 4.450821940088645 4.4254007975250715
1024 4.4254007975250715 4.41269785563145
2048 4.41269785563145 4.406348292032874
4096 4.406348292032874 4.403173987070718
8192 4.403173987070718 4.40158695379893
16384 4.40158695379893 4.400793466965357
32768 4.400793466965357 4.400396730999152
65536 4.400396730999152 4.400198364878694
131072 4.400198364878694 4.400099182284126
262144 4.400099182284126 4.400049591103258
524288 4.400049591103258 4.400024795541928
